parameters:
    logos_directory: '%kernel.project_dir%/public/uploads/logos'
    events_directory: '%kernel.project_dir%/public/uploads/events'
    cv_directory: '%kernel.project_dir%/public/uploads/cv'
    profiles_directory: '%kernel.project_dir%/public/uploads/profiles'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'