# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    logos_directory: '%kernel.project_dir%/public/uploads/logos'
    events_directory: '%kernel.project_dir%/public/uploads/events'
    cv_directory: '%kernel.project_dir%/public/uploads/cv'
    profiles_directory: '%kernel.project_dir%/public/uploads/profiles'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, listeners, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'